trigger:
- main

pool:
  vmImage: ubuntu-latest
strategy:
  matrix:
    Python310:
      python.version: '3.10'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
    addToPath: true
    architecture: 'x64'
  displayName: 'Use Python $(python.version)'

- script: |
    python -m venv antenv 
    source antenv/bin/activate
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: $(System.DefaultWorkingDirectory)
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true

- task: CopyFiles@2
  inputs:
    SourceFolder: './static'  # Specify the path to your static files directory
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/static'  # Destination folder in the artifact
    CleanTargetFolder: true
    OverWrite: true
  displayName: 'Copy static files'

- publish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
  displayName: 'Upload package'
  artifact: drop
